### ISSUE TITLE
Can you give a full example on how to write Event.yml?

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate-sample#2]
I can hardly understand the function of events, since the documentation is not quite clear on the issue. 
More over, I am not sure about how to set deadline on homework, thanks.

**Comment by inducer** [comment]
- I've updated the docs on events. I hope they are clearer now: http://documen.tician.de/relate/content.html#calendar-and-events
- The code in [this section](http://documen.tician.de/relate/content.html#the-calendear-information-file-events-yml) is a full example of `events.yml`.
- The docs now include a full example on how to set a deadline for a flow: http://documen.tician.de/relate/flow.html

Hope this helps!

**Comment by dzhuang** [comment]
Thanks a lot, I will read it through.
